name: 'Start interop'
description: 'Generates interop token and creates pending status'
inputs:
  status-app-id:
    description: 'Status-reporting GitHub App ID'
    required: true
  status-app-private-key:
    description: 'Status-reporting GitHub App private key'
    required: true
  requesting-owner:
    description: "Owner of repository containing the event SHA"
    required: true
  requesting-repository:
    description: "Repository containing the event SHA"
    required: true
  job-name:
    description: 'Name of the job to report to the requesting repository'
    required: true
outputs:
  app-token:
    description: 'Access token for updating the pending status'
    value: ${{ steps.app-token.outputs.token }}
runs:
  using: 'composite'
  steps:
    - name: Generate app token
      if: endsWith(github.event.action, '-interop-request')
      id: app-token
      uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
      with:
        app-id: ${{ inputs.status-app-id }}
        private-key: ${{ inputs.status-app-private-key }}
        owner: ${{ inputs.requesting-owner }}
        repositories: ${{ inputs.requesting-repository }}

    - name: Create pending status
      if: endsWith(github.event.action, '-interop-request')
      shell: sh
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
        OWNER: ${{ inputs.requesting-owner }}
        REPOSITORY: ${{ inputs.requesting-repository }}
        SHA: ${{ github.event.client_payload.sha }}
        JOB_NAME: ${{ inputs.job-name }}
      run: >
        gh api "repos/${OWNER}/${REPOSITORY}/statuses/${SHA}"
        --field state=pending
        --field target_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        --field description="In progress"
        --field context="Integration tests / ${JOB_NAME}"
