name: Integration Tests book

on:
  push:
    branches:
      - main

permissions: {}
jobs:
  deploy:
    permissions:
      contents: write # to push pages branch (peaceiris/actions-gh-pages)

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dtolnay/rust-toolchain@stable
        id: toolchain
      - run: rustup override set ${{steps.toolchain.outputs.name}}

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@ee69d230fe19748b7abf22df32acaa93833fad08 # v2.0.0
        with:
          mdbook-version: 'latest'

      - name: Install mdbook-katex
        run: cargo install mdbook-katex

      - name: Build Integration Tests book
        run: mdbook build doc/book/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/book/book
